language: node_js
node_js:
  - 11
  - 12

before_script:
  - cd ui
  - npm i
  - npm run-script build
  

after_success:
  - cd ui
  - npm i -g codecov
  - codecov

jobs:
  include:
    - services:
        - docker
      script:
        - docker build .