language: node_js
node_js:
  - 11

before_script:
  - cd ui
  - npm ci

jobs:
  include:
    - stage: Build
      script:
        - npm run-script build
    - stage: Test
      script:
        - npm run-script lint
        - npm test -- --coverage --watchAll=false
        - npm i -g codecov
        - codecov
    - stage: Test Docker
      services:
        - docker
      script:
        - docker build .
    - stage: Deploy
      script:
        - docker build . -t spotypop/kitty_hash_ui:$TRAVIS_BUILD_NUMBER
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push spotypop/kitty_hash_ui:$TRAVIS_BUILD_NUMBER

stages:
  - name: Test
    # require the type to be a PR
    if: type = pull_request
  - name: Build
    # require the type to be a PR
    if: type = pull_request
  - name: Test Docker
    # require the type to be a PR
    if: type = pull_request
  - name: Deploy
    # require the type to be push to master
    if: type = push AND branch = master