language: node_js
node_js:
  - 11
  - 12

before_script:
  - npm i --prefix ./ui/
  - npm run-script build --prefix ./ui/

after_success:
  - cd ui
  - npm i -g codecov
  - codecov

jobs:
  include:
    - services:
        - docker
      script:
        - docker build ./ui/ -f ./ui/Dockerfile