language: node_js
node_js:
  - 11
  - 12

before_script:
  - cd ui
  - npm i
  - npm run-script build
  
script:
  - npm run-script lint
  - npm test -- --coverage --watchAll=false

after_success:
  - cd ui
  - npm i -g codecov
  - codecov

jobs:
  include:
    - stage: Test Docker
      services:
        - docker
      script:
        - docker build .
    - stage: Deploy
      if: branch = master
      script:
        - echo 'deploy me'