version: '3'
services:
  reverse-proxy:
    image: nginx:stable-alpine
    volumes:
    - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports: 
    - "80:80"
  ui:
    build: ./ui
    ports:
    - "3000:80"
  liquidsoap:
    build: ./liquidsoap
    image: spotypop/kitty_hash_liquidsoap:stable
    command: ["/script/script.liq"]
    volumes:
    - /Users/shebeko/Music/liquidsoap/lofi:/music:ro
    environment:
    - TZ=Israel/Jerusalem
    - ICECAST_SOURCE_PASSWORD=hackme
    - ICECAST_MOUNT_NAME=basic-radio
  icecast:
    image: infiniteproject/icecast:latest
    environment:
    - ICECAST_HOSTNAME=icecast
    - ICECAST_SOURCE_PASSWORD=hackme
    - ICECAST_ADMIN_USERNAME=admin
    - ICECAST_ADMIN_PASSWORD=passw0rd
    ports:
    - "8000:8000"