apiVersion: v1
kind: Service
metadata:
  name: icecast
spec:
  type: {{ .Values.icecast.service.type }}
  selector:
    app: icecast
  ports:
    - protocol: TCP
      port: {{ .Values.icecast.service.port }}