apiVersion: apps/v1
kind: Deployment
metadata:
  name: icecast-deployment
  labels:
    app: icecast
spec:
  replicas: {{ .Values.icecast.replicaCount }}
  selector:
    matchLabels:
      app: icecast
  template:
    metadata:
      labels:
        app: icecast
    spec:
      containers:
      - name: icecast
        image: infiniteproject/icecast:{{ .Values.icecast.version }}
        env:
        - name: ICECAST_SOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: icecastsource
              key: ICECAST_SOURCE_PASSWORD
        - name: ICECAST_ADMIN_USERNAME
          valueFrom:
              secretKeyRef:
                name: icecastadmin
                key: ICECAST_ADMIN_USERNAME
        - name: ICECAST_ADMIN_PASSWORD
          valueFrom:
              secretKeyRef:
                name: icecastadmin
                key: ICECAST_ADMIN_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /status-json.xsl
            port: 8000
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /status-json.xsl
            port: 8000
          periodSeconds: 1

      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}