apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: external-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - kittyhash.com
    secretName: kittyhash-tls
  rules:
  - host: kittyhash.com
    http:
      paths:
      - path: /basic-radio
        backend:
          serviceName: icecast
          servicePort: {{ .Values.icecast.service.port }}
      - path: /status-json.xsl
        backend:
          serviceName: icecast
          servicePort: {{ .Values.icecast.service.port }}
      - backend:
          serviceName: ui-service
          servicePort: {{ .Values.ui.service.port }}
